- hosts: all
  tasks:
  - name: deploy
    command: python scripts/destroy.py --network {{ network }} --contractAbi {{ abi }} --privateKey {{ privateKey }} --address {{ address }} --destroyFunction {{ destroy_function }} --refund {{ refund }}