- hosts: all
  tasks:
  - name: deploy
    command: python scripts/deploy_upgradablebeacon.py --network {{ network }} --privateKey {{ privateKey }} --abi {{ abi }} --implementationAddress {{ implementationAddress }}
    register: contract_address
  - name: Set attributes
    set_stats:
      data:
        contract_address: "{{ contract_address.stdout_lines[-1] }}" 