- hosts: all
  tasks:
  - name: deploy
    command: python scripts/deploy_implementation.py --network {{ network }} --contractAbi {{ contractAbi }} --privateKey {{ privateKey }}
    register: contract_address
  - name: Set attributes
    set_stats:
      data:
        contract_address: "{{ contract_address.stdout_lines[-1] }}"