- hosts: all
  tasks:
  - name: deploy
    command: python scripts/deploy_proxy_beacon.py --network {{ network }} --privateKey {{ privateKey }} --abi {{ abi }} --beaconAddress {{ beaconAddress }} --proxyCount {{ proxyCount }} 
    register: contract_address
  - name: Set attributes
    set_stats:
      data:
        contract_address: "{{ contract_address.stdout_lines[-1] }}" 