- hosts: all
  tasks:
  - name: install web3
    pip: 
      name: web3==5.28.0
  - name: deploy
    command: python scripts/diamond.py --network {{ network }} --contractAbi {{ abi }} --privateKey {{ privateKey }} {{ facets }}
    register: contract_address
  - name: Set attributes
    set_stats:
      data:
        contract_address: "{{ contract_address.stdout }}"