/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHookCoveredCallFactory,
  IHookCoveredCallFactoryInterface,
} from "../../../contracts/interfaces/IHookCoveredCallFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "instrumentAddress",
        type: "address",
      },
    ],
    name: "CoveredCallInstrumentCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
    ],
    name: "getCallInstrument",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "assetAddress",
        type: "address",
      },
    ],
    name: "makeCallInstrument",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHookCoveredCallFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IHookCoveredCallFactoryInterface {
    return new Interface(_abi) as IHookCoveredCallFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHookCoveredCallFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IHookCoveredCallFactory;
  }
}
