/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as transparentUpgradableProxySol from "./TransparentUpgradableProxy.sol";
export type { transparentUpgradableProxySol };
export type { Implementation1 } from "./Implementation1";
export type { Implementation2 } from "./Implementation2";
export type { ProxyAdmin } from "./ProxyAdmin";
