/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Font1 } from "./Font1";
export type { Font2 } from "./Font2";
export type { Font3 } from "./Font3";
