/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DecimalMath } from "./DecimalMath";
export type { SignedDecimalMath } from "./SignedDecimalMath";
