/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SignedDecimalMathInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRECISE_UNIT"
      | "UNIT"
      | "decimals"
      | "highPrecisionDecimals"
      | "preciseUnit"
      | "unit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PRECISE_UNIT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "UNIT", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "highPrecisionDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "preciseUnit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unit", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PRECISE_UNIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UNIT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "highPrecisionDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preciseUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unit", data: BytesLike): Result;
}

export interface SignedDecimalMath extends BaseContract {
  connect(runner?: ContractRunner | null): SignedDecimalMath;
  waitForDeployment(): Promise<this>;

  interface: SignedDecimalMathInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRECISE_UNIT: TypedContractMethod<[], [bigint], "view">;

  UNIT: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  highPrecisionDecimals: TypedContractMethod<[], [bigint], "view">;

  preciseUnit: TypedContractMethod<[], [bigint], "view">;

  unit: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRECISE_UNIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "highPrecisionDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "preciseUnit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unit"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
