/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1822Proxiable__factory>;
    getContractFactory(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1271__factory>;
    getContractFactory(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967__factory>;
    getContractFactory(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Upgrade__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Burnable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortStrings__factory>;
    getContractFactory(
      name: "HookBeaconProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookBeaconProxy__factory>;
    getContractFactory(
      name: "HookBidPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookBidPool__factory>;
    getContractFactory(
      name: "HookCoveredCallFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookCoveredCallFactory__factory>;
    getContractFactory(
      name: "HookCoveredCallImplV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookCoveredCallImplV1__factory>;
    getContractFactory(
      name: "HookERC721MultiVaultImplV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookERC721MultiVaultImplV1__factory>;
    getContractFactory(
      name: "HookERC721VaultFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookERC721VaultFactory__factory>;
    getContractFactory(
      name: "HookERC721VaultImplV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookERC721VaultImplV1__factory>;
    getContractFactory(
      name: "HookProtocol",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookProtocol__factory>;
    getContractFactory(
      name: "HookUpgradeableBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookUpgradeableBeacon__factory>;
    getContractFactory(
      name: "IDelegationRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDelegationRegistry__factory>;
    getContractFactory(
      name: "IERC721FlashLoanReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721FlashLoanReceiver__factory>;
    getContractFactory(
      name: "IHookCoveredCall",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookCoveredCall__factory>;
    getContractFactory(
      name: "IHookCoveredCallFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookCoveredCallFactory__factory>;
    getContractFactory(
      name: "IHookERC20Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookERC20Vault__factory>;
    getContractFactory(
      name: "IHookERC721Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookERC721Vault__factory>;
    getContractFactory(
      name: "IHookERC721VaultFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookERC721VaultFactory__factory>;
    getContractFactory(
      name: "IHookOption",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookOption__factory>;
    getContractFactory(
      name: "IHookProtocol",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookProtocol__factory>;
    getContractFactory(
      name: "IHookVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHookVault__factory>;
    getContractFactory(
      name: "IInitializeableBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInitializeableBeacon__factory>;
    getContractFactory(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWETH__factory>;
    getContractFactory(
      name: "IPropertyValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPropertyValidator__factory>;
    getContractFactory(
      name: "Font1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Font1__factory>;
    getContractFactory(
      name: "Font2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Font2__factory>;
    getContractFactory(
      name: "Font3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Font3__factory>;
    getContractFactory(
      name: "BlackScholes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BlackScholes__factory>;
    getContractFactory(
      name: "FixedPointMathLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FixedPointMathLib__factory>;
    getContractFactory(
      name: "DecimalMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DecimalMath__factory>;
    getContractFactory(
      name: "SignedDecimalMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignedDecimalMath__factory>;
    getContractFactory(
      name: "TokenURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenURI__factory>;
    getContractFactory(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712__factory>;
    getContractFactory(
      name: "HookInstrumentERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HookInstrumentERC721__factory>;
    getContractFactory(
      name: "PermissionConstants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PermissionConstants__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "IERC1822Proxiable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1822Proxiable>;
    getContractAt(
      name: "IERC1271",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1271>;
    getContractAt(
      name: "IERC1967",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967>;
    getContractAt(
      name: "IERC5267",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267>;
    getContractAt(
      name: "IBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "ERC1967Upgrade",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Upgrade>;
    getContractAt(
      name: "Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "ERC721Burnable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Burnable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "EIP712",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ShortStrings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortStrings>;
    getContractAt(
      name: "HookBeaconProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookBeaconProxy>;
    getContractAt(
      name: "HookBidPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookBidPool>;
    getContractAt(
      name: "HookCoveredCallFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookCoveredCallFactory>;
    getContractAt(
      name: "HookCoveredCallImplV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookCoveredCallImplV1>;
    getContractAt(
      name: "HookERC721MultiVaultImplV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookERC721MultiVaultImplV1>;
    getContractAt(
      name: "HookERC721VaultFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookERC721VaultFactory>;
    getContractAt(
      name: "HookERC721VaultImplV1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookERC721VaultImplV1>;
    getContractAt(
      name: "HookProtocol",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookProtocol>;
    getContractAt(
      name: "HookUpgradeableBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookUpgradeableBeacon>;
    getContractAt(
      name: "IDelegationRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDelegationRegistry>;
    getContractAt(
      name: "IERC721FlashLoanReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721FlashLoanReceiver>;
    getContractAt(
      name: "IHookCoveredCall",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookCoveredCall>;
    getContractAt(
      name: "IHookCoveredCallFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookCoveredCallFactory>;
    getContractAt(
      name: "IHookERC20Vault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookERC20Vault>;
    getContractAt(
      name: "IHookERC721Vault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookERC721Vault>;
    getContractAt(
      name: "IHookERC721VaultFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookERC721VaultFactory>;
    getContractAt(
      name: "IHookOption",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookOption>;
    getContractAt(
      name: "IHookProtocol",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookProtocol>;
    getContractAt(
      name: "IHookVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHookVault>;
    getContractAt(
      name: "IInitializeableBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInitializeableBeacon>;
    getContractAt(
      name: "IWETH",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWETH>;
    getContractAt(
      name: "IPropertyValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPropertyValidator>;
    getContractAt(
      name: "Font1",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Font1>;
    getContractAt(
      name: "Font2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Font2>;
    getContractAt(
      name: "Font3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Font3>;
    getContractAt(
      name: "BlackScholes",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BlackScholes>;
    getContractAt(
      name: "FixedPointMathLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FixedPointMathLib>;
    getContractAt(
      name: "DecimalMath",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DecimalMath>;
    getContractAt(
      name: "SignedDecimalMath",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SignedDecimalMath>;
    getContractAt(
      name: "TokenURI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenURI>;
    getContractAt(
      name: "EIP712",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712>;
    getContractAt(
      name: "HookInstrumentERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HookInstrumentERC721>;
    getContractAt(
      name: "PermissionConstants",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PermissionConstants>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "IERC1822Proxiable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1271>;
    deployContract(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Upgrade",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Upgrade>;
    deployContract(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "ERC721Burnable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721Burnable>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortStrings>;
    deployContract(
      name: "HookBeaconProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookBeaconProxy>;
    deployContract(
      name: "HookBidPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookBidPool>;
    deployContract(
      name: "HookCoveredCallFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookCoveredCallFactory>;
    deployContract(
      name: "HookCoveredCallImplV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookCoveredCallImplV1>;
    deployContract(
      name: "HookERC721MultiVaultImplV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookERC721MultiVaultImplV1>;
    deployContract(
      name: "HookERC721VaultFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookERC721VaultFactory>;
    deployContract(
      name: "HookERC721VaultImplV1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookERC721VaultImplV1>;
    deployContract(
      name: "HookProtocol",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookProtocol>;
    deployContract(
      name: "HookUpgradeableBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookUpgradeableBeacon>;
    deployContract(
      name: "IDelegationRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDelegationRegistry>;
    deployContract(
      name: "IERC721FlashLoanReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721FlashLoanReceiver>;
    deployContract(
      name: "IHookCoveredCall",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookCoveredCall>;
    deployContract(
      name: "IHookCoveredCallFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookCoveredCallFactory>;
    deployContract(
      name: "IHookERC20Vault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookERC20Vault>;
    deployContract(
      name: "IHookERC721Vault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookERC721Vault>;
    deployContract(
      name: "IHookERC721VaultFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookERC721VaultFactory>;
    deployContract(
      name: "IHookOption",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookOption>;
    deployContract(
      name: "IHookProtocol",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookProtocol>;
    deployContract(
      name: "IHookVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookVault>;
    deployContract(
      name: "IInitializeableBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInitializeableBeacon>;
    deployContract(
      name: "IWETH",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWETH>;
    deployContract(
      name: "IPropertyValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPropertyValidator>;
    deployContract(
      name: "Font1",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Font1>;
    deployContract(
      name: "Font2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Font2>;
    deployContract(
      name: "Font3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Font3>;
    deployContract(
      name: "BlackScholes",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlackScholes>;
    deployContract(
      name: "FixedPointMathLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedPointMathLib>;
    deployContract(
      name: "DecimalMath",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecimalMath>;
    deployContract(
      name: "SignedDecimalMath",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignedDecimalMath>;
    deployContract(
      name: "TokenURI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenURI>;
    deployContract(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "HookInstrumentERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookInstrumentERC721>;
    deployContract(
      name: "PermissionConstants",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PermissionConstants>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "IERC1822Proxiable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1822Proxiable>;
    deployContract(
      name: "IERC1271",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1271>;
    deployContract(
      name: "IERC1967",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IERC5267",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Upgrade",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Upgrade>;
    deployContract(
      name: "Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "ERC721Burnable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721Burnable>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "EIP712",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ShortStrings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortStrings>;
    deployContract(
      name: "HookBeaconProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookBeaconProxy>;
    deployContract(
      name: "HookBidPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookBidPool>;
    deployContract(
      name: "HookCoveredCallFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookCoveredCallFactory>;
    deployContract(
      name: "HookCoveredCallImplV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookCoveredCallImplV1>;
    deployContract(
      name: "HookERC721MultiVaultImplV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookERC721MultiVaultImplV1>;
    deployContract(
      name: "HookERC721VaultFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookERC721VaultFactory>;
    deployContract(
      name: "HookERC721VaultImplV1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookERC721VaultImplV1>;
    deployContract(
      name: "HookProtocol",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookProtocol>;
    deployContract(
      name: "HookUpgradeableBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookUpgradeableBeacon>;
    deployContract(
      name: "IDelegationRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDelegationRegistry>;
    deployContract(
      name: "IERC721FlashLoanReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721FlashLoanReceiver>;
    deployContract(
      name: "IHookCoveredCall",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookCoveredCall>;
    deployContract(
      name: "IHookCoveredCallFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookCoveredCallFactory>;
    deployContract(
      name: "IHookERC20Vault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookERC20Vault>;
    deployContract(
      name: "IHookERC721Vault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookERC721Vault>;
    deployContract(
      name: "IHookERC721VaultFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookERC721VaultFactory>;
    deployContract(
      name: "IHookOption",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookOption>;
    deployContract(
      name: "IHookProtocol",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookProtocol>;
    deployContract(
      name: "IHookVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHookVault>;
    deployContract(
      name: "IInitializeableBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInitializeableBeacon>;
    deployContract(
      name: "IWETH",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWETH>;
    deployContract(
      name: "IPropertyValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPropertyValidator>;
    deployContract(
      name: "Font1",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Font1>;
    deployContract(
      name: "Font2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Font2>;
    deployContract(
      name: "Font3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Font3>;
    deployContract(
      name: "BlackScholes",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BlackScholes>;
    deployContract(
      name: "FixedPointMathLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FixedPointMathLib>;
    deployContract(
      name: "DecimalMath",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DecimalMath>;
    deployContract(
      name: "SignedDecimalMath",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignedDecimalMath>;
    deployContract(
      name: "TokenURI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenURI>;
    deployContract(
      name: "EIP712",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "HookInstrumentERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HookInstrumentERC721>;
    deployContract(
      name: "PermissionConstants",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PermissionConstants>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
