/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IHookCoveredCallFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "getCallInstrument" | "makeCallInstrument"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CoveredCallInstrumentCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getCallInstrument",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeCallInstrument",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCallInstrument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeCallInstrument",
    data: BytesLike
  ): Result;
}

export namespace CoveredCallInstrumentCreatedEvent {
  export type InputTuple = [
    assetAddress: AddressLike,
    instrumentAddress: AddressLike
  ];
  export type OutputTuple = [assetAddress: string, instrumentAddress: string];
  export interface OutputObject {
    assetAddress: string;
    instrumentAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IHookCoveredCallFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IHookCoveredCallFactory;
  waitForDeployment(): Promise<this>;

  interface: IHookCoveredCallFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCallInstrument: TypedContractMethod<
    [assetAddress: AddressLike],
    [string],
    "view"
  >;

  makeCallInstrument: TypedContractMethod<
    [assetAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCallInstrument"
  ): TypedContractMethod<[assetAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "makeCallInstrument"
  ): TypedContractMethod<[assetAddress: AddressLike], [string], "nonpayable">;

  getEvent(
    key: "CoveredCallInstrumentCreated"
  ): TypedContractEvent<
    CoveredCallInstrumentCreatedEvent.InputTuple,
    CoveredCallInstrumentCreatedEvent.OutputTuple,
    CoveredCallInstrumentCreatedEvent.OutputObject
  >;

  filters: {
    "CoveredCallInstrumentCreated(address,address)": TypedContractEvent<
      CoveredCallInstrumentCreatedEvent.InputTuple,
      CoveredCallInstrumentCreatedEvent.OutputTuple,
      CoveredCallInstrumentCreatedEvent.OutputObject
    >;
    CoveredCallInstrumentCreated: TypedContractEvent<
      CoveredCallInstrumentCreatedEvent.InputTuple,
      CoveredCallInstrumentCreatedEvent.OutputTuple,
      CoveredCallInstrumentCreatedEvent.OutputObject
    >;
  };
}
