/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721FlashLoanReceiver } from "./IERC721FlashLoanReceiver";
export type { IHookCoveredCall } from "./IHookCoveredCall";
export type { IHookCoveredCallFactory } from "./IHookCoveredCallFactory";
export type { IHookERC721Vault } from "./IHookERC721Vault";
export type { IHookERC721VaultFactory } from "./IHookERC721VaultFactory";
export type { IHookProtocol } from "./IHookProtocol";
export type { IHookVault } from "./IHookVault";
export type { IInitializeableBeacon } from "./IInitializeableBeacon";
export type { IWETH } from "./IWETH";
