/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Font1__factory } from "./Font1__factory";
export { Font2__factory } from "./Font2__factory";
export { Font3__factory } from "./Font3__factory";
