/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fontsSol from "./Fonts.sol";
export type { fontsSol };
export type { TokenURI } from "./TokenURI";
